### ISSUE TITLE
Node keeps trying to connect to non-repsonsive nodes.

### ISSUE THREAD

**Issue by frohal** [AidosKuneen/aidos-node#1]
When starting up with -p, I get a list of nodes to connect to, apparently.
But a few of those is not responding correctly - some gives 'connetion refused' and some gives 'connect time out'
This is ofc OK. What is not OIK, is that my node retries the same connections the next second...

This way mo log is cluttered with connection-error-entries... 
Is there a negative cache that is missing ?

It should at least me 5 mins before retrying timeout-nodes, and I'd prefer an hour for 'connection refused'-nodes.

**Comment by Nos-Manus** [comment]
Non responding peers are removed from the peerlist every 5 minutes if they are unresponsive.
The error messages in the log are from broadcasting and can happen in several cases:
1. A node has too many packets queued to receive -> dropped
2. Broadcasting only functions if both peers have each other in their peerlist. So if ports of your node are non-reachable the sends will time out / be refused because you are not in the other nodes peerlist. (Updates after 5 minutes too)
In both cases this is not an issue.
The message you got wasn't supposed to be on log level error as this is something that can happen more frequently. I pushed an update so please pull the newest version.

Also change the loglevel in "/src/main/resources/logback.xml" to "INFO" level as you are not debugging. (Bottom part you can see how to do it in the commented out code)
